// Generated by FlutterFire CLI.
// TODO: Run `flutterfire configure` in this directory to populate real values.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions not configured for '
          '${defaultTargetPlatform.name}. Run flutterfire configure.',
        );
    }
  }

  // TODO: Replace appId with the web app ID from the Firebase console.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhvjp0-SUGeoS_K-gqlwNOCZWjMjwzhlQ',
    appId: '1:145423397513:web:TODO_RESPONDER',
    messagingSenderId: '145423397513',
    projectId: 'mission-out-deuce',
    authDomain: 'mission-out-deuce.firebaseapp.com',
    storageBucket: 'mission-out-deuce.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhvjp0-SUGeoS_K-gqlwNOCZWjMjwzhlQ',
    appId: '1:145423397513:android:b62977eee05c8e9f284c58',
    messagingSenderId: '145423397513',
    projectId: 'mission-out-deuce',
    authDomain: 'mission-out-deuce.firebaseapp.com',
    storageBucket: 'mission-out-deuce.firebasestorage.app',
  );
}
