// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5llLCZUF4ndzIpJIM6k2V3-utaqhYaio',
    appId: '1:145423397513:web:95ee335d6f409637284c58',
    messagingSenderId: '145423397513',
    projectId: 'mission-out-deuce',
    authDomain: 'mission-out-deuce.firebaseapp.com',
    storageBucket: 'mission-out-deuce.firebasestorage.app',
    measurementId: 'G-EMV4EFWJDD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhvjp0-SUGeoS_K-gqlwNOCZWjMjwzhlQ',
    appId: '1:145423397513:android:b62977eee05c8e9f284c58',
    messagingSenderId: '145423397513',
    projectId: 'mission-out-deuce',
    storageBucket: 'mission-out-deuce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDenwgDbtsL8sSz_zxnbXDDr4oBUv__tws',
    appId: '1:145423397513:ios:34a7f7bd7f0e946f284c58',
    messagingSenderId: '145423397513',
    projectId: 'mission-out-deuce',
    storageBucket: 'mission-out-deuce.firebasestorage.app',
    iosClientId: '145423397513-096a4b9390evusknfmlk0fg65gjbqpuk.apps.googleusercontent.com',
    iosBundleId: 'com.missionout.responder',
  );

}