// Generated by FlutterFire CLI.
// TODO: Run `flutterfire configure` in this directory to populate real values.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    throw UnsupportedError(
      'DefaultFirebaseOptions not configured for '
      '${defaultTargetPlatform.name}. Run flutterfire configure.',
    );
  }

  // TODO: Replace appId with the web app ID from the Firebase console
  // (Firebase console → Project settings → Your apps → Web app).
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhvjp0-SUGeoS_K-gqlwNOCZWjMjwzhlQ',
    appId: '1:145423397513:web:TODO_DISPATCHER',
    messagingSenderId: '145423397513',
    projectId: 'mission-out-deuce',
    authDomain: 'mission-out-deuce.firebaseapp.com',
    storageBucket: 'mission-out-deuce.firebasestorage.app',
  );
}
